<?php

/**
 * @file
 * Contains layout_per_node.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\field_layout\Display\EntityDisplayWithLayoutInterface;
use Drupal\layout_per_node\LayoutEditorBuilder;

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Add "Layout" to primary tabs.
 */
function layout_per_node_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  // Ensure that an update to the node "edit" form invalidates this cache.
  // @see layout_per_node_form_node_type_edit_form_alter().
  $cacheability->addCacheTags(['layout_per_node:tabs']);
  // Ensure the user's permissions & appropriate query args invalidate cache.
  $cache = [
    'contexts' => [
      'user.permissions',
      'route',
      'url.query_args:layout-editor',
      'url.query_args:layout',
    ],
  ];
  if ($entity_id = \Drupal::service('layout_per_node.manager')->eligibleNode()) {
    $data['tabs'][0]['node.layout_editor'] = [
      '#theme' => 'menu_local_task',
      '#link' => [
        'title' => t('Layout'),
        'url' => Url::fromRoute('entity.node.canonical', ['node' => $entity_id], ['query' => ['layout-editor' => '1']]),
      ],
      '#cache' => $cache,
    ];
    $query = \Drupal::request()->query->all();
    // The user is in "Layout Editor" mode. Change title & url.
    if (isset($query['layout-editor'])) {
      $data['tabs'][0]['node.layout_editor']['#link'] = [
        'title' => t('Exit Layout'),
        'url' => Url::fromRoute('entity.node.canonical', ['node' => $entity_id], ['absolute' => TRUE]),
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * Save a layout entity with empty data upon initial node save.
 */
function layout_per_node_node_insert(EntityInterface $entity) {
  $config = \Drupal::config('layout_per_node.enabled');
  $enabled = $config->get($entity->getType());
  if ($enabled) {
    $layoutPerNodeManager = \Drupal::service('layout_per_node.manager');
    $layoutPerNodeManager->updateLayout($entity->id(), []);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Whenever node data is re-saved, a corresponding layout with VID must be
 * provided.
 */
function layout_per_node_node_update(EntityInterface $entity) {
  $config = \Drupal::config('layout_per_node.enabled');
  $enabled = $config->get($entity->getType());
  if ($enabled) {
    $new_revision = TRUE;
    // 1. First, we check that this is not an update triggered by "Save Layout",
    // since that will save the layout automatically.
    if ($entity->getRevisionLogMessage() != 'Layout updated') {
      $layoutPerNodeManager = \Drupal::service('layout_per_node.manager');
      $revert_to_revision = $entity->getLoadedRevisionId();
      // 2. Check if the operation is reverting to a previous revision.
      if ($revert_to_revision) {
        $layout = $layoutPerNodeManager->getLayoutEntity($entity->id(), $revert_to_revision);
        // 3. Check if the previous revision has layout data (first won't).
        if ($layout) {
          // A: Save the previous revision's layout data to this new revision.
          $layoutPerNodeManager->updateLayout($entity->id(), $layout->get('layout')->getValue());
        }
        else {
          // B: Save a layout_per_node revision with empty layout data.
          $layoutPerNodeManager->updateLayout($entity->id(), []);
        }
      }
      else {
        // C. Save a new layout revision with the same data as the previous VID.
        $layoutPerNodeManager->updateLayout($entity->id());
      }
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * When a node with layout data is deleted, delete the layout data.
 */
function layout_per_node_node_delete(EntityInterface $entity) {
  $query = \Drupal::entityQuery('layout_per_node_layout')
    ->condition('entity_id', $entity->id());
  $ids = $query->execute();
  if (!empty($ids)) {
    entity_delete_multiple('layout_per_node_layout', $ids);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Add an "Enable layout per node" checkbox to content type Edit form.
 */
function layout_per_node_form_node_type_edit_form_alter(&$form, FormStateInterface $form_state) {
  // Ensure that an update to the node "edit" form invalidates this cache.
  // @see layout_per_node_menu_local_tasks_alter.
  Cache::invalidateTags(['layout_per_node:tabs']);

  $node_type = $form_state->getBuildInfo()['callback_object']->getEntity();
  $config = \Drupal::config('layout_per_node.' . $node_type->id());
  $enabled = $config->get('enabled');
  $allowed = $config->get('allowed');
  $default_layouts = !empty($allowed) ? array_values($allowed) : [];
  $form['layout_editor'] = array(
    '#type' => 'details',
    '#title' => 'Layout Per Node',
    '#group' => 'additional_settings',
  );
  $form['layout_editor']['layout_per_node_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => 'Enable layout per node',
    '#default_value' => $enabled,
    '#description' => 'Allow users with access to create/edit this content type
    to use the drag-and-drop layout editor when viewing the node.',
  );
  $layoutPluginManager = \Drupal::service('plugin.manager.core.layout');
  foreach ($layoutPluginManager->getLayoutOptions() as $group => $layouts) {
    foreach ($layouts as $key => $value) {
      $available_layouts[$key] = $value;
    }
  }
  $form['layout_editor']['layout_per_node_allowed'] = [
    '#title' => 'Allowed Layouts',
    '#description' => '<h2>&#9432; If no layouts are selected, all will remain available.</h2>',
    '#type' => 'checkboxes',
    '#options' => $available_layouts,
    '#default_value' => $default_layouts,
    '#states' => [
      'invisible' => [
        ':input[name="layout_per_node_enabled"]' => ['checked' => FALSE],
      ],
    ],
  ];
  $form['actions']['submit']['#submit'][] = 'layout_per_node_node_type_edit_form_submit';
}

/**
 * Submit handler for node type forms.
 */
function layout_per_node_node_type_edit_form_submit($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $node_type = $form_state->getBuildInfo()['callback_object']->getEntity();
  $config = \Drupal::service('config.factory')->getEditable('layout_per_node.' . $node_type->id());
  if (isset($values['layout_per_node_enabled'])) {
    $config->set('enabled', $values['layout_per_node_enabled']);
    $config->save();
  }
  if (isset($values['layout_per_node_allowed'])) {
    $config->set('allowed', $values['layout_per_node_allowed']);
    $config->save();
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Move field_layout_entity_view_alter() to the end of the list.
 */
function layout_per_node_module_implements_alter(&$implementations, $hook) {
  if (in_array($hook, ['entity_view_alter', 'node_view_alter'])) {
    if (isset($implementations['field_layout'])) {
      $group = $implementations['field_layout'];
      unset($implementations['field_layout']);
      $implementations['field_layout'] = $group;
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 *
 * Overrides the default entity view display provided by field_layout for
 * eligible node types.
 */
function layout_per_node_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($display instanceof EntityDisplayWithLayoutInterface && $entity->getEntityType()->id() == 'node') {
    $enabled = \Drupal::config('layout_per_node.' . $entity->getType())->get('enabled');
    if ($enabled) {
      \Drupal::classResolver()->getInstanceFromDefinition(LayoutEditorBuilder::class)
        ->buildView($build, $display);
    }
  }
}
